### ISSUE TITLE
[DOC] Missing parameter

### ISSUE THREAD

**Issue by gitomato** [thephpleague/tactician#109]
Hello, 

I couldn't find the documentation repository.
On this page:
https://tactician.thephpleague.com/tweaking-tactician/

There is a missing parameter in a code sample:
`        new CommandHandlerMiddleware($locator, $inflector)`

Should be:
`        new CommandHandlerMiddleware($nameExtractor, $locator, $inflector)`

**Comment by rosstuck** [comment]
Hi @gitomato,

Thanks for catching this, hope it wasn't too annoying! 

The documentation repo is the same as this repo, but on the gh-docs branch (it's a common but unintuitive github thing). If you'd like to open a PR to fix it, I'm happy to merge it ASAP. 😄

**Comment by gitomato** [comment]
Oh, I didn't know that.
Ok, it's done!

**Comment by rosstuck** [comment]
No worries, it's not super easy to find. Thanks a ton for making a PR for it! 😄
