### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by alexbilbie** [thephpleague/tactician#11]
Hey @rosstuck,

Could you please tag a release even if it is just a 0.1.0?

Thanks!

**Comment by GrahamCampbell** [comment]
@alexbilbie I think even just adding a branch alias would be a good idea for now.

**Comment by rosstuck** [comment]
I'm open to doing it, but here's the thing: PR #10 is going to radically change the entire plugin setup and it's so very nearly plainfully close to done. So, what I'd like to do is finish that in the next 2 days, review, merge and tag 0.1 once that interface is settled. If you're willing to wait 2 more days, I can even release it with updated docs. :smile:

Would that be okay?

**Comment by alexbilbie** [comment]
Sure thing :+1:

**Comment by rosstuck** [comment]
Just tagged 0.3 :)

**Comment by alexbilbie** [comment]
Thanks, SemVer requires major.minor.patch formatting though (so in this instance should be 0.3.0).

**Comment by rosstuck** [comment]
Whoops, fixed!
