### ISSUE TITLE
V2: InMemoryLocator replacement?

### ISSUE THREAD

**Issue by simPod** [thephpleague/tactician#134]
I was using `InMemoryLocator` from v1 in my tests. What would be the proper replacement in v2?

**Comment by rosstuck** [comment]
https://github.com/thephpleague/tactician/blob/master/src/Handler/Mapping/MapByStaticList.php

This is basically the same except it requires the method name to be specified as well (was thinking of compiled containers here, mostly). I've thought about adding a MapByClassName where the first parameter is a method inflector and the second is an array mapping Command classes to Handler classes, that way you don't need to repeat the method name everytime.

I've also thought about creating a couple quick testing classes/builders as well, with a mock handler.

Lemme know if either of those sound appealing or if this is straightforward enough already.

**Comment by simPod** [comment]
I noticed the middleware now reads it from container anyway https://github.com/thephpleague/tactician/blob/master/src/Handler/CommandHandlerMiddleware.php#L39

With v1 I used to create command->callback maps in tests, will rewrite them.
