### ISSUE TITLE
Contribution file

### ISSUE THREAD

**Issue by NigelGreenway** [thephpleague/tactician#29]
Could we get a contribution file for the preferred process.

**Comment by rosstuck** [comment]
Good call! Most of the dev work is going to be on new plugin repos as well, so we should probably do something with League\Skeleton as well, I reckon...

I know that won't help with what you're working on right now though, but there's no special rules except the League ones about strict PSR-2, PSR-4 in general, etc.

**Comment by alexbilbie** [comment]
This is the contributing file I've always used https://github.com/thephpleague/oauth2-server/blob/master/CONTRIBUTING.md

**Comment by NigelGreenway** [comment]
Thank you.

**Comment by rosstuck** [comment]
I'm going to reopen this because it's a totally legit thing to ask for and we should write one at some point. :smile:

**Comment by NigelGreenway** [comment]
Yep, sorry. Clicked the wrong button...

**Comment by rosstuck** [comment]
Added thanks to @rtuin, thanks for the suggestions, fellas!
