### ISSUE TITLE
"If a command fires off more commands"

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician#35]
> If a command fires off more commands

This is from league/tactician-doctrine. I wonder how this is possible. It certainly is, but how? (Injecting the command bus into the handler?)

**Comment by rosstuck** [comment]
Yup.

You can't with the InMemoryLocator but with a lazy-loading version (which will be the standard in the future), it's possible. That said, I usually recommend folks extract the reusable parts of their Handlers rather than try composite commands together.
