### ISSUE TITLE
CommandBusAware

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician#37]
I'm sure you know what I mean. It should be in the core repo, shouldn't it?

**Comment by rosstuck** [comment]
I don't know what you mean. :) Are you referring to something like the League\Event trait that adds a property, setter and shortcut functions like `emit()`?

**Comment by sagikazarmark** [comment]
Yeah. 😁

**Comment by sagikazarmark** [comment]
Without a handlr method exposed. The point is that a commandbus is
injectable into an object.

**Comment by rosstuck** [comment]
To be honest, that's something I probably won't merge. I think it encourages folks adding mutable setters for things that really shouldn't be mutable in the first place and the saved code is minimal. Beyond that it locks you into a certain interface, which you may or may not want.

Thanks for the suggestion though, I appreciate it. :)
