### ISSUE TITLE
HasCommand helper class

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician#39]
Previously I proposed a `CommandBusAware` class, now I am proposing another: [HasCommand](https://github.com/thephpleague/tactician-command-events/blob/master/src/Event/HasCommand.php)

Actually a trait.

I would use it in both command events and bernard plugin and there can be numerous use cases. Is there room for it in the core package?

**Comment by rosstuck** [comment]
It saves only a small amount of code and requires a bit of extra cognitive overhead. I think I'll have to pass on this one. I'm not a huge fan of creating shortcut objects or traits, I'd rather have some small scale duplication. I appreciate the suggestion though, sorry. :)

**Comment by sagikazarmark** [comment]
I guessed the answer, just asked :+1:

**Comment by rosstuck** [comment]
I guessed you guessed but thanks for keeping on asking. :)
