### ISSUE TITLE
Self-installed PHPUnit doesn't work anymore

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician#51]
Since #48 it is impossible to run unit tests with a globally installed version of phpunit. Actually the best would be when everyone used the installed version by composer (vendor/bin/phpunit) to make sure that the right version is used.

To solve this issue I wrote a little bash script:

``` bash
#!/bin/bash

PHPUNIT="$PWD/vendor/bin/phpunit"

if [ -f $PHPUNIT ]; then
	$PHPUNIT $@
else
	$HOME/.bin/phpunit.local $@
fi
```

It looks for a composer installed version in the given path and runs that if found. Otherwise the global one is used.

**Comment by rosstuck** [comment]
Hmm, yeah, I'd prefer we only really support the composer installed version. To make it more intuitive, how about we add a little "Testing" section to the README, just like we have for some of the other plugins and as per the League template?

**Comment by sagikazarmark** [comment]
This script does exactly that.

Plugins created by me has already the Testing section. The reason I usually omit `vendor/bin/` from the testing command is that according to my experiences most people either install the phar or the composer package locally, thus they run phpunit without the path. Since it is a development dependency, it is the developers responsibility to check if the globally installed version satisfies the requirement.

**Comment by rosstuck** [comment]
README is updated to at least inform people, I'd rather not ship a bash script to run the proper testing command. If people really do it, we've got Travis to catch it.

**Comment by sagikazarmark** [comment]
I didn't want you to ship a bash script with the package. :stuck_out_tongue: 

This is just to inform people about the situation and gives a possible solution. The best way is to place this script into your PATH.

Also, this issue could be possibly linked from the readme.
