### ISSUE TITLE
Assert that array contains only Middleware

### ISSUE THREAD

**Issue by boekkooi** [thephpleague/tactician#54]
We should check this on https://github.com/thephpleague/tactician/blob/master/src/CommandBus.php#L24 or https://github.com/thephpleague/tactician/blob/master/src/CommandBus.php#L55

I know it's defensive but better to catch a stupid mistake when creating the chain then when executing it.

**Comment by rosstuck** [comment]
Good point, will definitely pick this up for the next release!
