### ISSUE TITLE
LockingMiddleware not running subsequent command

### ISSUE THREAD

**Issue by angun33** [thephpleague/tactician#60]
Looking at the LockingMiddleware source code, you didn't record the subsequent Command. Only the callable is stored. So when the `$nextPending` is called, the old Command is given instead. Looks like a bug to me.

I haven't actually tested this, just noticed it when I'm looking at the code.

**Comment by rosstuck** [comment]
Glancing at it pre-coffee, sounds right, but still need to confirm. Good eye and very sorry!

It sounds like a simple enough fix but we need to find a better testing strategy for this class, it's always been a bit touchy. Perhaps an integration test via the Command Bus would be easier...

I'll need to look at this one in more depth. If you'd like to take a crack at producing a unit test for it, I'd be more than glad to merge and review. If not, it might take me a few days to get to it but I appreciate your raising this issue nonetheless. Thanks!

**Comment by rosstuck** [comment]
Closing this one now that #62 is merged. Thanks a ton @angun33, we'll tag a new release soon to fix this. :smile:
