### ISSUE TITLE
Add security information to README

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician#72]
I think there is a league suggestion for that as well. How should we process with the plugins?

**Comment by rosstuck** [comment]
We can just add the boilerplate Security header to email me to each README. I'm not planning to do further joint plugin maintainers than the ones that are already established so I'd prefer if they just ran through me and then I can distribute them appropriately. I have to prioritize where I spend time these days but a security issue in Tactician would immediately land on the top of my pile.

Once it passes, we should do this in accordance with PSR-9: https://github.com/php-fig/fig-standards/blob/master/proposed/security-reporting-process.md

**Comment by sagikazarmark** [comment]
Fine by me.

**Comment by rosstuck** [comment]
PSR-9 seems fairly frozen. Adding basic security disclosures and reporting info to root package, will link to from plugins later today.
