### ISSUE TITLE
Plugin to prioritize command

### ISSUE THREAD

**Issue by RonRademaker** [thephpleague/tactician#82]
I created a plugin to prioritize commands. You can check it out at https://github.com/ConnectHolland/tactician-prioritycommand-plugin

**Comment by rosstuck** [comment]
Pretty interesting stuff, will take a closer look. At a glance, some of this (especially the Sequence part) seems closer to a Saga implementation. Have you seen the recent Saga implementation in Broadway? https://github.com/qandidate-labs/broadway/blob/master/examples/saga/ReservationSaga.php

**Comment by RonRademaker** [comment]
I can see how you make the comparison to saga, I hadn't seen the implementation. My goal with sequence commands wasn't to force a specific sequence but to make sure some command was executed before another. Where saga looks at this from a 'multiple requests per saga' point of view, the sequence command is nothing more than: do this before you do anything else (but feel free to wait). The main objective of these priority commands is to delay the execution of as many commands as possible to as late as possible to increase performance (at least from a user's perspective, in the end everything still has to happen and the commands won't run any faster because of this. But users will have received a response so everything seems faster).

**Comment by rosstuck** [comment]
Just a quick update, I've added this to the Community Plugin page alongside your Scheduler plugin. Hopefully that helps drive some folks your way. Thanks again for all your hard work! :)
