### ISSUE TITLE
Yii adapter for Tactician

### ISSUE THREAD

**Issue by pavelmics** [thephpleague/tactician#87]
Hello!
At first, thank you for creating Tactician, very simple and at the same time very powerfull tool.
Just now I work with large Yii based application and I need command-bus pattern in it, so I wrote [YiiTactition](https://github.com/pavelmics/YiiTactician) - simple Yii adapter for using Tactician in Yii application.

PS: sorry for my English :)

**Comment by rosstuck** [comment]
Your english is fine :) Thanks for your work integrating Tactician into more frameworks!

I'm on vacation right now but when I get back, I'll update the framework integrations page to include a link.

**Comment by rosstuck** [comment]
Adding shortly. :)
