### ISSUE TITLE
1.0 release ?

### ISSUE THREAD

**Issue by gitomato** [thephpleague/tactician#88]
Hello,

Thanks for your nice work on Tactician !
Do you know when you will release the 1.0 ?
What is missing to reach it ?

**Comment by rosstuck** [comment]
Thanks! At this point, 1.0 is delayed only by time, in two senses:

- First, seeing if any major issues surfaced from the design that needed to be fixed. 0.6.1 has been out there a while and nothing major has come up.
- Second, time on my end to go through, tag and update all the repos.

The first one is done, the second is probably a little ways out yet. I'm not 100% happy with the current design but it's stable and used enough that 1.0 is coming, it won't change much (if at all) and anything new or breaking will go into Tactician 2.0 :)

**Comment by gitomato** [comment]
Thanks for the answer, I guess I can close this "issue" !
