### ISSUE TITLE
Implement a League Container locator

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/tactician#9]

**Comment by sagikazarmark** [comment]
@rosstuck ping

**Comment by rosstuck** [comment]
@sagikazarmark Pong. I agree with this one, it'll need to be a separate package again. Definitely would like to have it, but would like to clear the decks of other issues first.

If anyone wants to start it, I'm definitely open to having it.

**Comment by sagikazarmark** [comment]
I put it on my secondary todo list, will see if I will have some time in the next few weeks.

**Comment by NigelGreenway** [comment]
I would be interested in picking this up if that is ok with you @sagikazarmark?, I am thinking that it would be the same(ish) code as #24 with a method of `addHandlersFromMapping(array $commandHandlerMap = [])`. If that is the case I can start tomorrow on my lunch to get the HandleLocator implemented?

**Comment by sagikazarmark** [comment]
@NigelGreenway go for it. ;)

However I am not sure I understand the solution you are proposing. As I can see @rosstuck commented on the referenced issue, maybe you two can agree on things.

**Comment by NigelGreenway** [comment]
Hi,

Just to let you know I have started on this over the weekend. Shall I submit a PR when I think I am ready for it to be discussed further?

**Comment by rosstuck** [comment]
Please do! Odds are we'll have to relocate it to another package but this will give us a chance to review and comment on it before we go through the hassle of creating another package. :)

**Comment by NigelGreenway** [comment]
Ok. It is in a testing/tweaking stage at the moment but should get chance to sort it this week.

**Comment by sagikazarmark** [comment]
Hm, I think it would be an overkill to have it in a separate package. Also, it's League internal, so a suggestion might not be an issue. @rosstuck thoughts?

@NigelGreenway anything you have?

**Comment by rosstuck** [comment]
It needs to be a separate package. The fact that's League internal is irrelevant, it's a separate package with it's own dependencies and version constraints that could conceivably evolve separate from Tactician itself. :smile: 

We do need to reduce the barrier to contributing packages, but that's a job for a tactician-skeleton or (better yet) some extra options to League\Skeleton. 

All that aside, I'm looking forward to this when it's Nigel's ready. :)

**Comment by NigelGreenway** [comment]
I'm thinking a separate package myself.

This could also tie in to other uses; for instance I have discussed reusing tactician for a package I am also prototyping for a Query Bus package that will work in the same way with the locator so I would be keen on separating it. :smiley: 

As with the work I am doing, trying to get it done for this weekend (Providing my 2yr old daughter doesn't keep trying to help/hinder coding :smile:  ).

**Comment by sagikazarmark** [comment]
Ask for her help. Trust me ;)

Little children know better. :smile:

**Comment by NigelGreenway** [comment]
Hi all,

Just to let you know that I have got so much done, but want to check with you guys that you are happy with it so far (my 1st real contribution to OSS).

I think there are some changes to be made along with additions but I am having a 'creativity block' the past 24 hours...

It can be found at https://github.com/NigelGreenway/tactician

Cheers

**Comment by sagikazarmark** [comment]
Seems to be fine. One comment: I didn't check it in detail, but as I can see you made some modifications to the InMemoryLocator. It should go into a separate PR.

**Comment by NigelGreenway** [comment]
Yeah I wasn't too sure. In the end I thought it would be the same PR as the ContainerLocator is taking responsibility of the InMemoryLocator?

**Comment by rosstuck** [comment]
@NigelGreenway Hey! At the core of things, your locator looks good and I'll check this week about getting a new plugin repo made with the league so we can start working on this. There's a few style things I'd tweak, such as removing the Yoda Conditionals and using the ::class constant, but it's a really strong start. :smile: 

That said, the changes to the InMemory locator aren't right for core. As we've discussed elsewhere, the InMemoryLocator (and others, for that matter) shouldn't create the handlers, only map to them. So, this commit ( https://github.com/NigelGreenway/tactician/commit/718e2d312a5c5b5aea5ed9b2147718323457cd81 ) probably should be reverted. 

Once we get the new `league/tactician-league-container` repo made (thoughts on the name? this naming is super awkward), let's make some PRs on the new repo and walk through polishing it up, step-by-step.

**Comment by NigelGreenway** [comment]
@rosstuck I have reverted the commit and will be implementing your tweaks. :smiley: 

I hate naming. Maybe if there was a standard like `league/<repo_name>-plugin-<plugin_name>` all plugins would be in unison.

I will do as @sagikazarmark suggested and create a new branch for a new PR for the InMemoryLocator changes to only return the class fqcn instead the class instance.

**Comment by NigelGreenway** [comment]
Ok, so I have reverted the changes, all tests pass and wanted a final checkup on my branch on letting me know you are happy for the PR.

Cheers

**Comment by sagikazarmark** [comment]
I am happy with it (except form a few minor exceptions):

* `[]` is not valid as a variable type, use `array` instead
* In the constructor the variable type and name are wrong, should be `Container $container`
* `if (false === ...` this is something that comes from symfony, personally I think it should be punished (but that is my personal opinion though)
* there should be an empty line between `@param`, `@return` and `@throws` blocks (just for readability)

**Comment by NigelGreenway** [comment]
That has been done.

The `[]`, `Container $container` and yoda style conditions were changed previously but have changed the rest.

_As with the Symfony part... guilty_ :smiley:

**Comment by sagikazarmark** [comment]
IMO throws should be the last as it is less important than the return value.

Also, not sure if return static should be return self or not. (ping @frankdejonge all I know about valid return tag values is from you)

But these are really not important ones

**Comment by NigelGreenway** [comment]
The only reason for `@return static` is that it was already in the current codebase for existing exceptions but I can change it if required?

**Comment by rosstuck** [comment]
@NigelGreenway Looking good! There's now a `league/tactician-container` repository for the final package. Can you extract the new Container locator from the Tactician repo and send a PR to this new repository with it?

You can find the new repo here: https://github.com/thephpleague/tactician-container/

We'll only want the stuff related to the new Container locator and its unit tests. Once we've got the PR merged in, I'll setup Travis/Scrutinizer/etc for the new repo and we'll make the final adjustments, docs, tweaks, etc. We're in the final stretch here, so thanks a lot for all of your work. :)

**Comment by NigelGreenway** [comment]
Hi all, 

Sorry for the delay, should get round to doing this some time this week.

**Comment by NigelGreenway** [comment]
@rosstuck Hi Dude, I do not have the ability to fork (due to it being empty I think?) the repository. Can you you let me know when the needed is sorted.

Cheers

Nigel

**Comment by rosstuck** [comment]
@NigelGreenway Check, added a README. :smile: You should be able to clone and send a PR now. I'll close this issue as well and we can pick everything up on that repo going forward.
